name: Hello World Action

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print Hello World
      run: echo "Hello World!"

    - name: List files in the repository
      run: ls ${{ github.workspace }}

    - name: Send Email to Committer
      run : |
        echo "The name of the pusher: ${{ github.event.pusher.name }}"
        echo "The email of the pusher: ${{ github.event.pusher.email }}"

    - name: Get Committer's Email
      id: get_committer_email
      run: |
        COMMITTER_EMAIL=$(git log -1 --pretty=format:'%ae')
        echo "Committer Email: $COMMITTER_EMAIL"
        echo "committer_email=$COMMITTER_EMAIL" >> $GITHUB_ENV