name: Hello World Action

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install msmtp
      run: |
        sudo apt-get update
        sudo apt-get install -y msmtp

    - name: Configure msmtp
      run: |
        echo "account default" > ~/.msmtprc
        echo "host smtp.office365.com" >> ~/.msmtprc
        echo "port 587" >> ~/.msmtprc
        echo "auth on" >> ~/.msmtprc
        echo "tls on" >> ~/.msmtprc
        echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" >> ~/.msmtprc
        echo "user ${{ secrets.OUTLOOK_USERNAME }}" >> ~/.msmtprc
        echo "password ${{ secrets.OUTLOOK_PASSWORD }}" >> ~/.msmtprc
        echo "from ${{ secrets.OUTLOOK_USERNAME }}" >> ~/.msmtprc
        echo "logfile ~/.msmtp.log" >> ~/.msmtprc
        echo "account default : default" >> ~/.msmtprc
        chmod 600 ~/.msmtprc


    - name: Print Hello World
      run: echo "Hello World!"

    - name: List files in the repository
      run: ls ${{ github.workspace }}

    - name: TRY Send Email to Committer
      run : |
        echo "The name of the pusher: ${{ github.event.pusher.name }}"
        echo "The email of the pusher: ${{ github.event.pusher.email }}"

    - name: TRY Get Committer's Email
      id: get_committer_email
      run: |
        COMMITTER_EMAIL=$(git log -1 --pretty=format:'%ae')
        echo "Committer Email: $COMMITTER_EMAIL"
        echo "committer_email=$COMMITTER_EMAIL" >> $GITHUB_ENV

    - name: Send Email

      run: |
        echo "Subject: Commit Notification" > email.txt
        echo "To:$COMMITTER_EMAIL" >> email.txt
        echo "Your recent commit was pushed to the repository!" >> email.txt
        msmtp --debug -a default $COMMITTER_EMAIL < email.txt