name: Get PR Commit Author Email

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get PR Last Commit Author Email via GitHub API
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        COMMITS_URL="https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/commits"

        # Hae commitit ja käytä jq:ta viimeisen commitin tekijän sähköpostin saamiseksi
        EMAIL=$(curl -s $COMMITS_URL | jq -r '.[-1].commit.author.email')

        if [ "$EMAIL" != "null" ]; then
          echo "PR last commit author email: $EMAIL"
        else
          echo "Email not found for PR last commit author"
        fi
